### PR TITLE
Multiple lock support

### PR DESCRIPTION
**Pull request by abouzek**
Tackles #4

### CODE REVIEW

**Comment by nfarina** [comment]
This is great! Could you make it a bit more user friendly though? What if we retained the old behavior of "if there's just one lock, assume that", but if there are multiple locks it could print them out and exit, so the user doesn't have to view source on the website?

**Comment by abouzek** [comment]
Sure, I can work on that sometime this week. I'm also considering making it a platform which automatically discovers every lock and adds them. Which do you think is best?

**Comment by abouzek** [comment]
Alright, made the change to print out lock IDs. My only solution for supporting commands to groups of locks was to add a 15 second delay between concurrent requests :(. Kevo's API does not seem to support rapid requests made to the API.

**Comment by nfarina** [comment]
Thanks for making these changes! This looks good to merge; I'll publish to npm as well. Thanks!

**Pull request merged**
